{% set name = "django-tinymce" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-tinymce-{{ version }}.tar.gz
  sha256: 13a63c81c5bb3683d135f5b1ec4c7da68bc880cf5138ffb266b608914ba12236

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - pip
  run:
    - python >=3.8
    - django >=3.2

test:
  imports:
    - tinymce
  commands:
    - pip check
  requires:
    - pip

about:
  summary: A Django application that contains a widget to render a form field as a TinyMCE editor
  home: https://github.com/jazzband/django-tinymce
  license: MIT
  license_file:
    - LICENSE.txt
    - tinymce/static/tinymce/license.txt

extra:
  recipe-maintainers:
    - mxr-conda
    - rxm7706
